site:
  title: Dfinity 日本語ドキュメント
  url: https://nifty-beaver-611cb8.netlify.app
  start_page: docs:introduction:welcome.adoc
content:
  sources:
    - url: .
      branches: HEAD
ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

asciidoc:
  attributes:
    platform: Internet Computer プラットフォーム
    IC: Internet Computer
    sdk-short-name: DFINITY Canister SDK
    sdk-long-name: DFINITY Canister Software Development Kit (SDK)
    proglang: Motoko
    company-id: DFINITY
